name: GET-UPDATE in different jobs with close code
on: 
  workflow_dispatch:

jobs:
  changeApproval:
    name: ServiceNow Change Approval
    runs-on: ubuntu-latest   
    steps:     
      - name: ServiceNow Change Approval
        uses: ServiceNow/servicenow-devops-change@dev
        id: create
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          # devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Change Approval'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","assignment_group":"a715cd759f2002002920bde8132e7018","description":"Automated Software Deployment.","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100'
          timeout: '3600'

  custom_action_get_change:
    needs: changeApproval
    runs-on: ubuntu-latest
    outputs:
      changeRequestNumber: ${{ steps.get.outputs.change-request-number }}
    name: GET change in custom_action_get_change job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4.0.0
        
      - name: ServiceNow Get Change
        uses: ServiceNow/servicenow-devops-get-change@dev  
        # Uses an action in the root directory
        id: get
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          # devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          change-details: '{"build_number":"","pipeline_name":"","stage_name":"ServiceNow Change Approval"}' #Working Version
      
      - name: Output of GET change
        run: echo "change-request-number = ${{ steps.get.outputs.change-request-number }}" >> $GITHUB_OUTPUT
        
  custom_action_update_change:
    needs: custom_action_get_change
    runs-on: ubuntu-latest
    name: UPDATE change in custom_action_update_change job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4.0.0
        
      - name: ServiceNow Update Change
        uses: ServiceNow/servicenow-devops-update-change@dev
        # Uses an action in the root directory
        id: update
        with:
          change-request-number: ${{needs.custom_action_get_change.outputs.changeRequestNumber}}
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          # devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          change-request-details: '{ "short_description":"Updated short_description abcdefghijklmnopqrstuvwxyz"}' #Working Version
      
      - name: Output of UPDATE change
        run: echo "The Status of Update Change Request Details => ${{ steps.update.outputs.status }}"  
