name: Nested Pipeline workflow

on: workflow_dispatch

jobs:
  preBuild:
    name: Pre Build
    runs-on: ubuntu-latest
    
    steps:
      - run: echo Run Pre Build

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [preBuild]
    
    steps:
      - run: echo Run Build
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
      
      - name: Run JUnit Tests
        run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [preBuild]

    steps:
      - run: echo Run Test
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test] # This job depends on 'build' and 'test' jobs
    steps:
      - run: echo Run Deploy
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - run: echo Finish release

# Define a conditional job that runs only if 'test' job fails
  notify_failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [test]
    if: failure() # This job runs only if 'test' job fails

    steps:
      - name: Notify team on failure
        run: echo "Test job failed, please investigate."

# Define parallel jobs that run concurrently
  parallel_jobs:
    name: Parallel Jobs
    runs-on: ubuntu-latest
    needs: [build] # These jobs depend on 'build' job

    strategy:
      matrix:
        job1: [job1]
        job2: [job2]
        job3: [job3]
        job4: [job4]
        job5: [job5]
        job6: [job6]
        job7: [job7]
        job8: [job8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Run parallel job with echo
        run: |
          case ${{ matrix.job1 }} in
            1) echo "Running Job 1";;
          esac
          case ${{ matrix.job2 }} in
            1) echo "Running Job 2";;
          esac
          case ${{ matrix.job3 }} in
            1) echo "Running Job 3";;
          esac
          case ${{ matrix.job4 }} in
            1) echo "Running Job 4";;
          esac
          case ${{ matrix.job5 }} in
            1) echo "Running Job 5";;
          esac
          case ${{ matrix.job6 }} in
            1) echo "Running Job 6";;
          esac
          case ${{ matrix.job7 }} in
            1) echo "Running Job 7";;
          esac
          case ${{ matrix.job8 }} in
            1) echo "Running Job 8";;
          esac

  postDeploy:
    name: Post Deploy
    runs-on: ubuntu-latest
    needs: [test, deploy] # This job depends on 'deploy'
    steps:
      - run: echo Run Post Deploy
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true

  lastStep:
    name: Last Step
    runs-on: ubuntu-latest
    needs: [postDeploy] # This job depends on 'deploy'
    steps:
      - run: echo Run Post Deploy
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
